#!/usr/bin/env bash
set -euo pipefail

# DEPRECATED (2026-05-31):
# Dynamic graph training entrypoint is archived and disabled by default.
# Override only for legacy reproduction:
#   ALLOW_DEPRECATED_DYNAMIC_KG=1 bash run_qagnn__csqa_dynamic.sh
if [ "${ALLOW_DEPRECATED_DYNAMIC_KG:-0}" != "1" ]; then
  echo "[DEPRECATED] run_qagnn__csqa_dynamic.sh has been archived and is disabled by default."
  echo "[DEPRECATED] Reason: dynamic KG training showed major regression versus baseline QA-GNN."
  echo "[DEPRECATED] If you must run legacy pipeline, execute:"
  echo "  ALLOW_DEPRECATED_DYNAMIC_KG=1 bash run_qagnn__csqa_dynamic.sh"
  exit 2
fi

# Uses data/csqa/graph_dynamic/*.pk generated by run_graph_dynamic.sh
# Requires run_qagnn__csqa.sh to honor GRAPH_DIR_SUFFIX (already patched in this repo).
export GRAPH_DIR_SUFFIX="_dynamic"

# Optional: choose source for dynamic KG in log naming or downstream scripts.
export GRAPH_TAG="${GRAPH_TAG:-g_dynamic}"

bash run_qagnn__csqa.sh
